# Numpy Array operations

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:", arr[2:7])
print("With Step", arr[1:10:2])
print("Backward Indexing:", arr[-3])
print("Negative Indexing:", arr[-5:-1])

Basic Slicing: [3 4 5 6 7]
With Step [ 2  4  6  8 10]
Backward Indexing: 8
Negative Indexing: [6 7 8 9]


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                  [7,8,9]])

print("Specific Element:", arr_2d[1,2])
print("Entire row:", arr_2d[2])
print("Entire Column:", arr_2d[:,1])

Specific Element: 6
Entire row: [7 8 9]
Entire Column: [2 5 8]


## Sorting

In [5]:
unsorted_arr = np.array([3, 1, 4, 2, 5])
print("Sorted Array:", np.sort(unsorted_arr)   )

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D Array by Column:", np.sort(arr_2d_unsorted, axis=0))

Sorted Array: [1 2 3 4 5]
Sorted 2D Array by Column: [[1 1]
 [2 2]
 [3 3]]


## Filtering Array

In [6]:
number = np.array([1, 2, 3, 4, 5,6 , 7, 8, 9, 10])
even_numbers = number[number % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


## Filter and Mask

In [7]:
mask = number > 5
print("Numbers greater than 5:", number[mask])

Numbers greater than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [8]:
indices = [0,2,4]
print(number[indices])  # Output: [1 3 5]

where_result = np.where(number > 5)
print(where_result)  # Output: (array([5, 6, 7, 8, 9]),)
print("Np Where Result:", number[where_result])  # Output: [ 6  7  8  9 10]

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np Where Result: [ 6  7  8  9 10]


In [9]:
condition_array= np.where(number > 5, number*2, number)
print("Condition Array:", condition_array)  # Output: [ 1  2  3  4  5 12 14 16 18 20]

Condition Array: [ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined_arr = np.concatenate((arr1, arr2))
print("Combined Array:", combined_arr)  # Output: [1 2 3

Combined Array: [1 2 3 4 5 6]


## Array Compatibility

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,2])

print("Compatibility Check:", a.shape == b.shape)  # Output: True
print("Compatibility Check:", a.shape == c.shape)  # Output: False

Compatibility Check: True
Compatibility Check: False


## Adding element in Array

In [15]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("Array with New Row:\n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("Array with New Column:\n", with_new_col)



Array with New Row:
 [[1 2]
 [3 4]
 [5 6]]
Array with New Column:
 [[1 2 7]
 [3 4 8]]
