# Creating Series

In [3]:
import numpy as np

In [6]:
## Creating Array from List

In [13]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array: \n",arr_2d)

1D Array:  [1 2 3 4 5]
2D Array: 
 [[1 2 3]
 [4 5 6]]


### List vs Numpy Array

In [ ]:
py_list = [1,2,3]
print("Python list multiplication ", py_list*2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python list multiplication ", np_array*2)



Python list multiplication  [1, 2, 3, 1, 2, 3]
Python list multiplication  [2 4 6]


In [16]:
import time
start = time.time()

py_list = [i*2 for i in range(1000000)]
print('\n List operation time: ', time.time() - start)



start = time.time()
np_array = np.arange(1000000)*2
print('\n Numpy operation time: ', time.time() - start)


 List operation time:  0.17461609840393066

 Numpy operation time:  0.008948802947998047


### Creating array from Scratch

In [18]:
zeros = np.zeros((3,4))
print("Zeroes Array: \n", zeros)

Zeroes Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
num = np.full((2,2),7)
print("num Array: \n", num)


num Array: 
 [[7 7]
 [7 7]]


In [21]:
random_mat = np.random.random((2,3))
print("random_mat Array: \n", random_mat)


random_mat Array: 
 [[0.94308354 0.6088779  0.44557733]
 [0.49139534 0.4511058  0.05360609]]


## Vector, Matrix and Tensor

In [23]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: ", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
